name: Ruby Test Workflow

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  
  workflow_dispatch:  
    inputs:
      environment:
        description: 'Run workflow'
        required: true
        default: 'production'  
        
        
          

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      
      - name: Install dependencies
        run: |
          gem install rspec
          gem install rest-client
          gem install yaml
          gem install json

      
      - name: Run RSpec tests
        run: |
          rspec spec/apitests.rb
