name: Ruby Test Workflow

on:
  push:
    branches:
      - master  # Run the action on push to main, change if you're using another branch
  pull_request:
    branches:
      - master  # Trigger on pull request to main

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

    
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  
          bundler-cache: true  


      - name: Install dependencies
        run: |
          gem install rspec          
          gem install rest-client      
          gem install yaml           
          gem install json   
          

      - name: Run RSpec tests
        run: |
          rspec spec/apitests.rb 
