name: Ruby Test Workflow

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 
  workflow_dispatch:  
    inputs:
     environment:
        description: 'Select the environment to test in'
        required: true
        default: 'staging'  
        type: choice
        options:
        - staging
        - production
        - development

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

    
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  
          bundler-cache: true  

      
      - name: Install dependencies
        run: |
          gem install rspec          # Install RSpec for running tests
          gem install rest-client     # Install rest-client for API calls
          gem install yaml           # Install yaml (if needed)
          gem install json           # Install json (if needed)

      
      - name: Run RSpec tests
        run: |
          rspec spec/apitests.rb  # Run your specific test file
